apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: feijoa-app-pdb
  labels:
    app: feijoa-app
    environment: demo
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: feijoa-app

