apiVersion: v1
kind: Service
metadata:
  name: feijoa-app-service
  labels:
    app: feijoa-app
    environment: demo
spec:
  type: ClusterIP
  selector:
    app: feijoa-app
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
